---
title: "Program"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(lubridate)
library(googlesheets)

# Get program data
program_data <- gs_title("ysc2017") %>%
  gs_read("program_ext") %>% 
  select(-X9, -X10) %>% 
  rename(Time = X1)

```

```{r Placeholder code, include = F}
Monday <- program_data %>% 
  select(Time, Monday)

Tuesday <- program_data %>% 
  select(Time, X3, Tuesday, X5) %>% 
  rename(Session = X3,
         Title = X5)
  
Wednesday <- program_data %>% 
  select(Time, X6, Wednesday, X8) %>% 
  rename(Session = X6,
         Title = X8)

```


# Monday 

```{r}
Monday %>% knitr::kable()
```

# Tuesday

```{r}
Tuesday %>% knitr::kable()
```

# Wednesday

```{r}
Wednesday %>% knitr::kable()
```


```{r Munge data, include=FALSE}
# Collapse columns so we can gather by day.
# prog_long <- program_data %>% 
#   mutate(Tuesday = paste(X3, Tuesday, X5, sep = "_"),
#          Wednesday = paste(X6, Wednesday, X8, sep = "_")) %>% 
#   select(Time, Monday, Tuesday, Wednesday) %>% 
#   gather(key = day,
#          value = event,
#          -Time) 

# prog_test <- prog_long %>%
#   filter(day != "Monday") %>% 
#   separate(event, into = c("Session", "Name", "Title"), 
#            by =  "[._]|[._]|[._]")


```
