---
title: "Registration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Registration for the Young Statisticians Conference 2017 is now open. [Click here to register to attend YSC2017](https://statsoc.360membershipcrm.com.au/member/eventreg.php?eid=NDQ). 

***

For those of us who are new to this conference thing, **everyone** who would like to attend (even if you're not presenting) must [register]((https://statsoc.360membershipcrm.com.au/member/eventreg.php?eid=NDQ)) for this conference and **only those who wish to present** a talk or poster need to submit an [abstract](https://docs.google.com/forms/d/e/1FAIpQLScb9AN4J6odAa8HleA_fsKJ_vG_Ukn7XMM4Dz_Cv67z0jGjTA/viewform).

***

If you are not a member and would like to be added to the mailing list for this event, please register your details [here](https://docs.google.com/forms/d/e/1FAIpQLScrtwxu4CRayb7iUTjwX7zQJUarav-D2kOXRV-SVX8LTXmJOA/viewform).

# Registration Fees:

*Earlybird: Payment before or on 6 August 2017:*

- Student and transitional members of SSA/NZSA* $100.00
- Non member students $140.00
- Members of SSA/NZSA $170.00
- Non members, non students $400.00

*Payment after 6 August 2017:*

- Student and transitional members of SSA/NZSA* $140.00
- Non member students $180.00
- Members of SSA/NZSA $220.00
- Non members, non students $450.00

*Student membership is available for $20.00 p/a. To join the Statistical Society of Australia, please click [here](https://statsoc.360membershipcrm.com.au/member/signup.php).

**Cancellation policy:**

Cancellations received prior to 19 September 2017 will be refunded in full. Confirmation of the refund having been processed will be emailed. Should additional documentation pertaining to the refund be required, a $20 administration fee will be charged. After Tuesday, 19 September 2017 no part of the registration fee will be refunded. However, registrations are transferable within the same organisation. Please advise any changes to eo@statsoc.org.au. 

<!-- *** -->
<!-- <div> -->
<!-- <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScb9AN4J6odAa8HleA_fsKJ_vG_Ukn7XMM4Dz_Cv67z0jGjTA/viewform?embedded=true" width="760" height="1000" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe> -->
<!-- </div>   -->